# Imports & Initialize DB Engine

In [20]:
#! pip3 install SQLAlchemy
#! pip3 install pymysql
#! pip3 install mysqlclient

In [21]:
import pandas as pd
import pymysql
import datetime
# import pandas.io.sql as psql
# import mysql.connector as connection
# import sqlalchemy as sql
# import _mysql

In [47]:
from sqlalchemy import create_engine

connect_string = 'mysql://rk_admin:rk2admin!@localhost/ol7'
engine = create_engine("mysql+pymysql://rk_admin:rk2admin!@localhost/ol7?autocommit=true")
from sqlalchemy import text
conn = engine.connect()
# sql_engine = sql.create_engine(connect_string)

# Create Models / Insert into Reference Tables (MODEL & MODEL_EXP)

In [59]:
op_tv_list = ["0", "1", "1.5", "2", "2.5", "3"]
op_iv_list = ["0", "1", "1.5", "2", "2.5", "3"]
cl_tv_list = ["0.5", "1", "1.5"]
model_id = 1

for op_tv in op_tv_list:
    for op_iv in op_iv_list:
        for cl_tv in cl_tv_list:
            stmt = "INSERT IGNORE INTO `model` (model_id, sample_per_hr, op_tv, op_iv, cl_tv, cl_iv) VALUES (" + str(model_id) + ", 6, " + \
                    op_tv + ", " + op_iv + ", " + cl_tv + ", " + " null )"
            results = conn.execute(text(stmt))
            # print ( model_id, ":" , results.rowcount, results.lastrowid)
            # print (stmt)
            # print (results)
            model_id += 1

In [60]:
# get last n expiry days
EXPIRY_DAYS = "10"
df = pd.read_sql_query("select distinct expiry "
                       "from option_list ol, option_quote oq "
                       "where oq.con_id = ol.con_id "
                       "order by 1 desc limit " + EXPIRY_DAYS, engine)
expiry_list = df["expiry"].values
for exp in expiry_list:
    stmt = "INSERT IGNORE INTO model_exp (model_id, expiry) select model_id, " + exp.strftime("%Y%m%d") +" from model"
    # print (exp, stmt)
    results = conn.execute(text(stmt))
    # print ( model_id, ":" , results.rowcount, results.lastrowid)

In [61]:
df = pd.read_sql_query("select * from model", engine)
df

     model_id  sample_per_hr  op_tv  op_iv  cl_tv cl_iv
0           1              6    0.0    0.0    0.5  None
1           2              6    0.0    0.0    1.0  None
2           3              6    0.0    0.0    1.5  None
3           4              6    0.0    1.0    0.5  None
4           5              6    0.0    1.0    1.0  None
..        ...            ...    ...    ...    ...   ...
103       104              6    3.0    2.5    1.0  None
104       105              6    3.0    2.5    1.5  None
105       106              6    3.0    3.0    0.5  None
106       107              6    3.0    3.0    1.0  None
107       108              6    3.0    3.0    1.5  None

[108 rows x 6 columns]

In [65]:
df = pd.read_sql_query("select expiry, count(*) runs from model_exp group by expiry", engine)
df

       expiry  runs
0  2023-03-17   108
1  2023-03-24   108
2  2023-03-31   108
3  2023-04-06   108
4  2023-04-14   108
5  2023-06-02   108
6  2023-06-09   108
7  2023-06-16   108
8  2023-06-23   108
9  2025-01-17   108

In [73]:
,
df = pd.read_sql_query("select model_id, count(*) runs from model_exp group by model_id", engine)
rows = df['runs'].sum()
print ("total rows = ", rows)
df

total rows =  1080

     model_id  runs
0           1    10
1           2    10
2           3    10
3           4    10
4           5    10
..        ...   ...
103       104    10
104       105    10
105       106    10
106       107    10
107       108    10

[108 rows x 2 columns]

# call open_options

In [69]:
model_id = "1"
print("matching CALL options by expiration date AND OPEN TV/IV " + model_id)

stmt = " select count(oq.id) from option_quote oq, option_list ol, stock_quote sq, model m " + \
" where oq.con_id = ol.con_id  and ol.expiry=m.expiry " + \
" and oq.id not in (select oq.id from model_run r where r.model_id = " +  model_id + " )" + \
" and oq.quote_date = sq.quote_date" + \
" and option_type = 'C'" + \
" and oq.open_tv >= ifnull(m.op_tv, oq.open_tv)" + \
" and oq.iv >= ifnull(m.op_iv, oq.iv)" + \
" and m.model_id = " + p_model_id

df = pd.read_sql_query(stmt, engine)
df

matching CALL options by expiration date AND OPEN TV/IV 1

ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'ol7.model_run' doesn't exist")
[SQL:  select count(oq.id) from option_quote oq, option_list ol, stock_quote sq, model m  where oq.con_id = ol.con_id  and ol.expiry=m.expiry  and oq.id not in (select oq.id from model_run r where r.model_id = 1 ) and oq.quote_date = sq.quote_date and option_type = 'C' and oq.open_tv >= ifnull(m.op_tv, oq.open_tv) and oq.iv >= ifnull(m.op_iv, oq.iv) and m.model_id = 1]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
stmt = "call model_open( " + p_model_id + " )"
print (stmt + ";" )
x = conn.execute(text(stmt))
x

In [ ]:
print("matching CALL options by expiration date AND OPEN TV/IV " + p_model_id)

stmt = \
" select m.expiry, date(quote_date) open_date, count(distinct oq.con_id) contracts, count(*) quotes , count(distinct mr.cl_oq_id) closed" + \
" from model m, model_run mr,  option_quote oq, option_list ol" + \
" where m.model_id = mr.model_id" + \
" and mr.model_id = " + p_model_id + \
" and oq.id = mr.op_oq_id" + \
" and oq.con_id = ol.con_id" + \
" group by m.expiry, date(quote_date)" + \
" order by 1,2,3"

df = pd.read_sql_query(stmt, engine)
print (df[["quotes", "closed"]].sum())
df