# Imports & Initialize DB Engine

In [20]:
#! pip3 install SQLAlchemy
#! pip3 install pymysql
#! pip3 install mysqlclient

In [21]:
import pandas as pd
import pymysql
import datetime
# import pandas.io.sql as psql
# import mysql.connector as connection
# import sqlalchemy as sql
# import _mysql

In [47]:
from sqlalchemy import create_engine

connect_string = 'mysql://rk_admin:rk2admin!@localhost/ol7'
engine = create_engine("mysql+pymysql://rk_admin:rk2admin!@localhost/ol7?autocommit=true")
from sqlalchemy import text
conn = engine.connect()
# sql_engine = sql.create_engine(connect_string)

# Create Models / Insert into Reference Tables (MODEL & MODEL_EXP)

In [59]:
op_tv_list = ["0", "1", "1.5", "2", "2.5", "3"]
op_iv_list = ["0", "1", "1.5", "2", "2.5", "3"]
cl_tv_list = ["0.5", "1", "1.5"]
model_id = 1

for op_tv in op_tv_list:
    for op_iv in op_iv_list:
        for cl_tv in cl_tv_list:
            stmt = "INSERT IGNORE INTO `model` (model_id, sample_per_hr, op_tv, op_iv, cl_tv, cl_iv) VALUES (" + str(model_id) + ", 6, " + \
                    op_tv + ", " + op_iv + ", " + cl_tv + ", " + " null )"
            results = conn.execute(text(stmt))
            # print ( model_id, ":" , results.rowcount, results.lastrowid)
            # print (stmt)
            # print (results)
            model_id += 1

In [60]:
# get last n expiry days
EXPIRY_DAYS = "10"
df = pd.read_sql_query("select distinct expiry "
                       "from option_list ol, option_quote oq "
                       "where oq.con_id = ol.con_id "
                       "order by 1 desc limit " + EXPIRY_DAYS, engine)
expiry_list = df["expiry"].values
for exp in expiry_list:
    stmt = "INSERT IGNORE INTO model_exp (model_id, expiry) select model_id, " + exp.strftime("%Y%m%d") +" from model"
    # print (exp, stmt)
    results = conn.execute(text(stmt))
    # print ( model_id, ":" , results.rowcount, results.lastrowid)

In [61]:
df = pd.read_sql_query("select * from model", engine)
df

     model_id  sample_per_hr  op_tv  op_iv  cl_tv cl_iv
0           1              6    0.0    0.0    0.5  None
1           2              6    0.0    0.0    1.0  None
2           3              6    0.0    0.0    1.5  None
3           4              6    0.0    1.0    0.5  None
4           5              6    0.0    1.0    1.0  None
..        ...            ...    ...    ...    ...   ...
103       104              6    3.0    2.5    1.0  None
104       105              6    3.0    2.5    1.5  None
105       106              6    3.0    3.0    0.5  None
106       107              6    3.0    3.0    1.0  None
107       108              6    3.0    3.0    1.5  None

[108 rows x 6 columns]

In [65]:
df = pd.read_sql_query("select expiry, count(*) runs from model_exp group by expiry", engine)
df

       expiry  runs
0  2023-03-17   108
1  2023-03-24   108
2  2023-03-31   108
3  2023-04-06   108
4  2023-04-14   108
5  2023-06-02   108
6  2023-06-09   108
7  2023-06-16   108
8  2023-06-23   108
9  2025-01-17   108

In [73]:
,
df = pd.read_sql_query("select model_id, count(*) runs from model_exp group by model_id", engine)
rows = df['runs'].sum()
print ("total rows = ", rows)
df

total rows =  1080

     model_id  runs
0           1    10
1           2    10
2           3    10
3           4    10
4           5    10
..        ...   ...
103       104    10
104       105    10
105       106    10
106       107    10
107       108    10

[108 rows x 2 columns]

# call open_options

In [79]:
model_id = "1"
print("matching CALL options by expiration date AND OPEN TV/IV " + model_id)

stmt = '''
select m.model_id, m. op_tv, op_iv, mr.run_id,
	DATE(oq.quote_date) quote_date, "->",
    ol.con_id,
    ol.strike,
    me.expiry,
    "->",
    min(oq.id) oq_id_min,
    count(*) oq_quotes,
    "->",
    format(avg(sq.trade_average),2) sq_avg,
    format(avg(oq.trade_average),2) oq_avg,
    format(avg(close_tv),2) cl_tv, format(avg(open_tv),2) op_tv, format(avg(iv),2) op_iv
from model m, model_exp_run mr, model_exp me, option_quote oq, stock_quote sq, option_list ol
where mr.op_oq_id = oq.id
and mr.run_id = me.run_id
and m.model_id = me.model_id
and oq.con_id = ol.con_id
and oq.quote_date = sq.quote_date
and ol.expiry = date("20230616")
group by m.model_id, m. op_tv, op_iv, mr.run_id, me.expiry,
	DATE(oq.quote_date),
    ol.con_id
order by model_id, expiry desc, con_id, quote_date desc;
'''
df = pd.read_sql_query(stmt, engine)
df

matching CALL options by expiration date AND OPEN TV/IV 1

,model_id,op_tv,op_iv,run_id,quote_date,->,con_id,strike,expiry,->,oq_id_min,oq_quotes,->,sq_avg,oq_avg,cl_tv,op_tv,op_iv
0,1,0.0,0.0,255,2023-06-02,->,478648721,170.0,2023-06-16,->,10242428,1,->,180.99,11.90,1.00,0.81,10.99
1,1,0.0,0.0,255,2023-06-01,->,478648721,170.0,2023-06-16,->,10119206,10,->,179.35,10.55,1.22,1.06,9.35
2,1,0.0,0.0,255,2023-05-31,->,478648721,170.0,2023-06-16,->,10018158,8,->,178.49,9.98,1.57,1.40,8.49
3,1,0.0,0.0,255,2023-05-30,->,478648721,170.0,2023-06-16,->,10036766,10,->,177.43,9.11,1.75,1.60,7.43
4,1,0.0,0.0,255,2023-05-26,->,478648721,170.0,2023-06-16,->,10002794,7,->,174.90,7.29,2.46,2.36,4.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,1,0.0,0.0,255,2023-06-02,->,632433941,177.5,2023-06-16,->,10257214,15,->,180.37,5.24,2.37,2.29,2.87
60,1,0.0,0.0,255,2023-06-01,->,632433941,177.5,2023-06-16,->,10133160,9,->,179.28,4.72,2.99,2.92,1.78
61,1,0.0,0.0,255,2023-05-31,->,632433941,177.5,2023-06-16,->,10032103,14,->,178.59,4.56,3.45,3.45,1.09
62,1,0.0,0.0,255,2023-05-30,->,632433941,177.5,2023-06-16,->,10050734,2,->,177.62,4.00,3.86,3.86,0.12
63,1,0.0,0.0,255,2023-06-05,->,632434011,182.5,2023-06-16,->,10229975,8,->,183.44,4.11,3.22,3.22,0.94

In [ ]:
df = pd.read_sql_query("select model_id from model", engine)
for x in df["model_id"].values:
    stmt = "call model_open( " + str(x) + " )"
    print (stmt)
    x = conn.execute(text(stmt))

call model_open( 1 )
call model_open( 2 )
call model_open( 3 )
call model_open( 4 )
call model_open( 5 )
call model_open( 6 )
call model_open( 7 )
call model_open( 8 )
call model_open( 9 )
call model_open( 10 )
call model_open( 11 )
call model_open( 12 )
call model_open( 13 )
call model_open( 14 )
call model_open( 15 )
call model_open( 16 )
call model_open( 17 )
call model_open( 18 )
call model_open( 19 )
call model_open( 20 )
call model_open( 21 )
call model_open( 22 )
call model_open( 23 )
call model_open( 24 )
call model_open( 25 )
call model_open( 26 )
call model_open( 27 )
call model_open( 28 )
call model_open( 29 )
call model_open( 30 )
call model_open( 31 )

In [ ]:
print("matching CALL options by expiration date AND OPEN TV/IV " + p_model_id)

stmt = \
" select m.expiry, date(quote_date) open_date, count(distinct oq.con_id) contracts, count(*) quotes , count(distinct mr.cl_oq_id) closed" + \
" from model m, model_run mr,  option_quote oq, option_list ol" + \
" where m.model_id = mr.model_id" + \
" and mr.model_id = " + p_model_id + \
" and oq.id = mr.op_oq_id" + \
" and oq.con_id = ol.con_id" + \
" group by m.expiry, date(quote_date)" + \
" order by 1,2,3"

df = pd.read_sql_query(stmt, engine)
print (df[["quotes", "closed"]].sum())
df