# Imports & Initialize DB Engine

In [12]:
#! pip3 install SQLAlchemy
#! pip3 install pymysql
#! pip3 install mysqlclient

In [13]:
import pandas as pd
import pymysql
import datetime
# import pandas.io.sql as psql
# import mysql.connector as connection
# import sqlalchemy as sql
# import _mysql

In [14]:
from sqlalchemy import create_engine

connect_string = 'mysql://rk_admin:rk2admin!@localhost/ol7'
engine = create_engine("mysql+pymysql://rk_admin:rk2admin!@localhost/ol7?autocommit=true")
from sqlalchemy import text
conn = engine.connect()
# sql_engine = sql.create_engine(connect_string)

# Create Models / Insert into Reference Tables (MODEL & MODEL_EXP)

In [15]:
op_tv_list = ["1", "2", "2.5", "3"]
op_iv_list = ["1", "2", "2.5", "3"]
cl_list = ["0.5", "1", "1.5"]
model_id = 1

for op_tv in op_tv_list:
    for op_iv in op_iv_list:
        for cl in cl_list:
            stmt = "INSERT IGNORE INTO `model` (model_id, sample_per_hr, op_tv, op_iv, cl_tv, cl_iv) VALUES (" + str(model_id) + ", 4, " + \
                    op_tv + ", " + op_iv + ", " + cl + ", " + " null )"
            results = conn.execute(text(stmt))
            model_id += 1
            stmt = "INSERT IGNORE INTO `model` (model_id, sample_per_hr, op_tv, op_iv, cl_iv, cl_tv) VALUES (" + str(model_id) + ", 4, " + \
                    op_tv + ", " + op_iv + ", " + cl + ", " + " null )"
            results = conn.execute(text(stmt))
            model_id += 1

In [16]:
# get last n expiry days
EXPIRY_DAYS = "100"
df = pd.read_sql_query("select distinct expiry "
                       "from option_list ol, option_quote oq "
                       "where oq.con_id = ol.con_id "
                       "order by 1 desc limit " + EXPIRY_DAYS, engine)
expiry_list = df["expiry"].values
for exp in expiry_list:
    stmt = "INSERT IGNORE INTO model_exp (model_id, expiry) select model_id, " + exp.strftime("%Y%m%d") +" from model"
    # print (exp, stmt)
    results = conn.execute(text(stmt))
    # print ( model_id, ":" , results.rowcount, results.lastrowid)
print("done")

done

In [17]:
df = pd.read_sql_query("select * from model", engine)
df

    model_id  sample_per_hr  op_tv  op_iv  cl_tv  cl_iv
0          1              4    1.0    1.0    0.5    NaN
1          2              4    1.0    1.0    NaN    0.5
2          3              4    1.0    1.0    1.0    NaN
3          4              4    1.0    1.0    NaN    1.0
4          5              4    1.0    1.0    1.5    NaN
..       ...            ...    ...    ...    ...    ...
91        92              4    3.0    3.0    NaN    0.5
92        93              4    3.0    3.0    1.0    NaN
93        94              4    3.0    3.0    NaN    1.0
94        95              4    3.0    3.0    1.5    NaN
95        96              4    3.0    3.0    NaN    1.5

[96 rows x 6 columns]

In [18]:
df = pd.read_sql_query("select expiry, count(*) runs from model_exp group by expiry", engine)
df

        expiry  runs
0   2022-11-18    96
1   2022-11-25    96
2   2022-12-02    96
3   2022-12-09    96
4   2022-12-16    96
5   2022-12-23    96
6   2022-12-30    96
7   2023-01-06    96
8   2023-01-13    96
9   2023-01-20    96
10  2023-01-27    96
11  2023-02-03    96
12  2023-02-10    96
13  2023-02-17    96
14  2023-02-24    96
15  2023-03-03    96
16  2023-03-10    96
17  2023-03-17    96
18  2023-03-24    96
19  2023-03-31    96
20  2023-04-06    96
21  2023-04-14    96
22  2023-06-02    96
23  2023-06-09    96
24  2023-06-16    96
25  2023-06-23    96
26  2023-06-30    96
27  2023-07-07    96
28  2023-07-14    96
29  2025-01-17    96

In [19]:
,
df = pd.read_sql_query("select model_id, count(*) runs from model_exp group by model_id", engine)
rows = df['runs'].sum()
print ("total rows = ", rows)
df

total rows =  2880

    model_id  runs
0          1    30
1          2    30
2          3    30
3          4    30
4          5    30
..       ...   ...
91        92    30
92        93    30
93        94    30
94        95    30
95        96    30

[96 rows x 2 columns]

# call open_options

In [20]:
model_id = "1"
print("matching CALL options by expiration date AND OPEN TV/IV " + model_id)

stmt = '''
select m.model_id, m. op_tv, op_iv, mr.run_id,
	DATE(oq.quote_date) quote_date, "->",
    ol.con_id,
    ol.strike,
    me.expiry,
    "->",
    min(oq.id) oq_id_min,
    count(*) oq_quotes,
    "->",
    format(avg(sq.trade_average),2) sq_avg,
    format(avg(oq.trade_average),2) oq_avg,
    format(avg(close_tv),2) cl_tv, format(avg(open_tv),2) op_tv, format(avg(iv),2) op_iv
from model m, model_exp_run mr, model_exp me, option_quote oq, stock_quote sq, option_list ol
where mr.op_oq_id = oq.id
and mr.run_id = me.run_id
and m.model_id = me.model_id
and oq.con_id = ol.con_id
and oq.quote_date = sq.quote_date
and ol.expiry = date("20230616")
group by m.model_id, m. op_tv, op_iv, mr.run_id, me.expiry,
	DATE(oq.quote_date),
    ol.con_id
order by model_id, expiry desc, con_id, quote_date desc;
'''
df = pd.read_sql_query(stmt, engine)
df

matching CALL options by expiration date AND OPEN TV/IV 1

,model_id,op_tv,op_iv,run_id,quote_date,->,con_id,strike,expiry,->,oq_id_min,oq_quotes,->,sq_avg,oq_avg,cl_tv,op_tv,op_iv
0,1,1.0,1.0,2815,2023-06-01,->,478648721,170.0,2023-06-16,->,10119213,7,->,179.21,10.37,1.25,1.09,9.21
1,1,1.0,1.0,2815,2023-05-31,->,478648721,170.0,2023-06-16,->,10018118,8,->,178.17,9.58,1.62,1.44,8.17
2,1,1.0,1.0,2815,2023-05-30,->,478648721,170.0,2023-06-16,->,10036767,5,->,177.26,9.01,1.80,1.65,7.26
3,1,1.0,1.0,2815,2023-05-26,->,478648721,170.0,2023-06-16,->,10002790,10,->,174.96,7.32,2.43,2.31,4.96
4,1,1.0,1.0,2815,2023-05-25,->,478648721,170.0,2023-06-16,->,10092804,15,->,172.79,5.97,3.23,3.15,2.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2887,96,3.0,3.0,2910,2023-05-11,->,478648721,170.0,2023-06-16,->,9979363,28,->,173.61,7.28,3.73,3.62,3.61
2888,96,3.0,3.0,2910,2023-05-10,->,478648721,170.0,2023-06-16,->,9992776,24,->,173.37,7.16,3.82,3.71,3.37
2889,96,3.0,3.0,2910,2023-05-09,->,478648721,170.0,2023-06-16,->,10011130,3,->,173.19,7.39,4.30,4.09,3.19
2890,96,3.0,3.0,2910,2023-05-08,->,478648721,170.0,2023-06-16,->,10052773,28,->,173.51,7.65,4.19,4.09,3.51
2891,96,3.0,3.0,2910,2023-05-24,->,632433805,167.5,2023-06-16,->,10061688,24,->,171.14,6.79,3.18,3.08,3.64

In [21]:
df = pd.read_sql_query("select model_id from model", engine)
rows = df.shape[0]
ctr = 0
print ("Start: " , datetime.datetime.now(), " rows: ", rows)
for x in df["model_id"].values:
    stmt = "call model_open( " + str(x) + " )"
    print (datetime.datetime.now(), ' [', ctr, "of", rows, "] ", stmt)
    ctr += 1
    x = conn.execute(text(stmt))
print (datetime.datetime.now(), ':  DONE')

Start:  2023-07-01 12:55:41.980956  rows:  96
2023-07-01 12:55:41.981110  [ 0 of 96 ]  call model_open( 1 )

KeyboardInterrupt:

In [ ]:
print("matching CALL options by expiration date AND OPEN TV/IV " , p_model_id)

stmt = '''
select m.model_id,  me.run_id, me.expiry, count(*) quotes
from model m, model_exp_run mr, model_exp me, option_quote oq, stock_quote sq, option_list ol
where mr.op_oq_id = oq.id
and mr.run_id = me.run_id
and m.model_id = me.model_id
and oq.con_id = ol.con_id
and oq.quote_date = sq.quote_date
-- and ol.expiry = date("20230616")
group by m.model_id, me.run_id,  me.expiry
order by me.expiry '''

df = pd.read_sql_query(stmt, engine)
print (" Total qutoes: ", df[["quotes"]].sum())
df

In [ ]:
df = pd.read_sql_query("select model_id from model", engine)
rows = df.shape[0]
ctr = 0
print ("Start: " , datetime.datetime.now(), " rows: ", rows)
for x in df["model_id"].values:
    stmt = "call model_close( " + str(x) + " )"
    print (datetime.datetime.now(), ' [', ctr, "of", rows, "] ", stmt)
    ctr += 1
    x = conn.execute(text(stmt))
print (datetime.datetime.now(), ':  DONE!')

## This is a title

more document

In [11]:
x = 3
print (x +2 )

5